Fixing veth iface name each time container is restarted

diff --git a/network-wrapper b/network-wrapper
--- a/network-wrapper
+++ b/network-wrapper
@@ -233,8 +233,18 @@ ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
 MTU=$(ip link show $IFNAME | awk '{print $5}')
 # If it's a bridge, we need to create a veth pair
 [ $IFTYPE = bridge ] && {
-    LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
-    GUEST_IFNAME="v${CONTAINER_IFNAME}pg${NSPID}"
+    # Issue: Local veth iface is not getting deleted when container is stopped/removed.
+    #         This is causing SSH Connection failures.
+    # Fux: Using same veth iface for a specific container.
+    # Using Mac address to bring uniqueness for the veth pairs getting created.
+    # Same VETH Pair name will always be used based on MAC Address.    
+    VETH_IFNAME="${MACADDR//:/}"
+    LOCAL_IFNAME="v${VETH_IFNAME}pl"
+    GUEST_IFNAME="v${VETH_IFNAME}pg"
+    VETH_PRESENT=$(ip link show dev $LOCAL_IFNAME  > /dev/null 2>&1; echo $?)
+    if [[ "$VETH_PRESENT" == "0" ]]; then
+            ip link delete dev $LOCAL_IFNAME
+    fi
     ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU
     case "$BRTYPE" in
         linux)
