Removed the dependancy on length of the GuestName

diff --git a/network-wrapper b/network-wrapper
--- a/network-wrapper
+++ b/network-wrapper
@@ -28,11 +28,15 @@ RUN_FILE=/var/run/network-wrapper
 
 # Get the human readable name of the container from container_id
 # This will be used to track assigned MACs, so re-creating or re-starting container will get same ip address
-STAT_GUEST=$(docker ps -a  --format "{{.ID}}" | grep ${GUESTNAME:0:12} >/dev/null 2>&1; echo $?)
+# GUESTNAME can be Container Name, or Short UUID or Long UUID.
+STAT_GUEST=$(docker inspect ${GUESTNAME} >/dev/null 2>&1; echo $?)
 if [[ "$STAT_GUEST" == "0" ]]; then
-    GUEST_LABEL_NAME=$(docker ps -a  --format "{{.ID}}\t{{.Names}}" | grep ${GUESTNAME:0:12} | awk '{print $NF}')
+    GUEST_LABEL_NAME=$(docker inspect ${GUESTNAME} --format='{{ .Name }}')
+    # Will return Guest Name as follows: /HSM_1_centos
+    GUEST_LABEL_NAME=${GUEST_LABEL_NAME:1}
 else
-    GUEST_LABEL_NAME=${GUESTNAME}
+    # Should we really continue ?
+    exit
 fi
 
 if [[ ! -e $RUN_FILE ]]; then
@@ -51,13 +55,13 @@ case "$1" in
       WAIT=1
       ;;
     inspect)
-      HWAddr=$(docker exec $GUESTNAME ip addr show eth0 |grep -E "ether" | awk '{print $2}')
-      Gateway=$(docker exec $GUESTNAME ip route list | grep default | awk '{print $3}')
-      IPAddress=$(docker exec $GUESTNAME ip addr show eth0 |grep -E "inet[ ]" | awk '{print $2}')
-      DNS=($(docker exec $GUESTNAME cat /etc/resolv.conf | grep nameserver | awk '{print $2}'))
+      HWAddr=$(docker exec $GUEST_LABEL_NAME ip addr show eth0 |grep -E "ether" | awk '{print $2}')
+      Gateway=$(docker exec $GUEST_LABEL_NAME ip route list | grep default | awk '{print $3}')
+      IPAddress=$(docker exec $GUEST_LABEL_NAME ip addr show eth0 |grep -E "inet[ ]" | awk '{print $2}')
+      DNS=($(docker exec $GUEST_LABEL_NAME cat /etc/resolv.conf | grep nameserver | awk '{print $2}'))
       Bridge=$(brctl show | head -2 | tail -1 |  awk '{print $1}')
       echo '{
-        "Container": "'$GUESTNAME'",
+        "Container": "'$GUEST_LABEL_NAME'",
         "NetworkSettings": {
           "HWAddr": "'$HWAddr'",
           "Bridge": "'$Bridge'",
@@ -65,7 +69,7 @@ case "$1" in
           "IPPrefixLen": "'$(echo $IPAddress |cut -d/ -f2)'",
           "Gateway": "'$Gateway'",
           "DNS": "'$(echo ${DNS[@]} | sed 's/\s/, /g')'",
-          "DHCP_PID": "'$(cat /var/run/dhclient-docker.$GUESTNAME.pid)'"
+          "DHCP_PID": "'$(cat /var/run/dhclient-docker.$GUEST_LABEL_NAME.pid)'"
 } }'
       exit 0
       ;;
@@ -153,7 +157,7 @@ done < /proc/mounts
 }
 
 # Try to find a cgroup matching exactly the provided name.
-N=$(find "$CGROUPMNT" -name "$GUESTNAME" | wc -l)
+N=$(find "$CGROUPMNT" -name "$GUEST_LABEL_NAME" | wc -l)
 case "$N" in
     0)
         # If we didn't find anything, try to lookup the container with Docker.
@@ -161,7 +165,7 @@ case "$N" in
         then
         RETRIES=3
         while [ $RETRIES -gt 0 ]; do
-            DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUESTNAME)
+            DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUEST_LABEL_NAME)
             [ $DOCKERPID != 0 ] && break
             sleep 1
             RETRIES=$((RETRIES - 1))
@@ -173,11 +177,11 @@ case "$N" in
         }
 
         [ "$DOCKERPID" = "<no value>" ] && {
-                echo "Container $GUESTNAME not found, and unknown to Docker."
+                echo "Container $GUEST_LABEL_NAME not found, and unknown to Docker."
                 exit 1
         }
         else
-            echo "Container $GUESTNAME not found, and Docker not installed."
+            echo "Container $GUEST_LABEL_NAME not found, and Docker not installed."
             exit 1
         fi
         ;;
@@ -185,7 +189,7 @@ case "$N" in
         true
         ;;
     *)
-        echo "Found more than one container matching $GUESTNAME."
+        echo "Found more than one container matching $GUEST_LABEL_NAME."
         exit 1
         ;;
 esac
@@ -212,9 +216,9 @@ fi
 if [ $DOCKERPID ]; then
   NSPID=$DOCKERPID
 else
-  NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
+  NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUEST_LABEL_NAME" | head -n 1)/tasks)
   [ "$NSPID" ] || {
-      echo "Could not find a process inside container $GUESTNAME."
+      echo "Could not find a process inside container $GUEST_LABEL_NAME."
       exit 1
   }
 fi
@@ -238,7 +242,7 @@ MTU=$(ip link show $IFNAME | awk '{print $5}')
     #         This is causing SSH Connection failures.
     # Fux: Using same veth iface for a specific container.
     # Using Mac address to bring uniqueness for the veth pairs getting created.
-    # Same VETH Pair name will always be used based on MAC Address.    
+    # Same VETH Pair name will always be used based on MAC Address.
     VETH_IFNAME="${MACADDR//:/}"
     LOCAL_IFNAME="v${VETH_IFNAME}pl"
     GUEST_IFNAME="v${VETH_IFNAME}pg"
@@ -260,13 +264,12 @@ ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
 [ "$MACADDR" ] && ip netns exec $NSPID ip link set dev $CONTAINER_IFNAME address $MACADDR
 if [ "$IPADDR" = "dhcp" ]
 then
-    [ $DHCP_CLIENT = "udhcpc"  ] && ip netns exec $NSPID $DHCP_CLIENT -Si $CONTAINER_IFNAME -x hostname:$GUESTNAME ;
+    [ $DHCP_CLIENT = "udhcpc"  ] && ip netns exec $NSPID $DHCP_CLIENT -Si $CONTAINER_IFNAME -x hostname:$GUEST_LABEL_NAME ;
      if [ $DHCP_CLIENT = "dhclient"  ]
     then
-        SHORTGUESTNAME=${GUESTNAME:0:12}
-        # Removing -H option dependency, as this option is not supported in ubuntu. 
-        # in Centos/RHEL, this is an optional and not required. 
-        ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient-docker.$SHORTGUESTNAME.pid" $CONTAINER_IFNAME
+        # Removing -H option dependency, as this option is not supported in ubuntu.
+        # in Centos/RHEL, this is an optional and not required.
+        ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient-docker.$GUEST_LABEL_NAME.pid" $CONTAINER_IFNAME
     fi
 else
     echo "only udhcpc / dhclient currently supported"
@@ -276,7 +279,7 @@ fi
 # Give our ARP neighbors a nudge about the new interface
 if which arping > /dev/null 2>&1
 then
-    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $(docker exec $GUESTNAME ip addr show eth0 |grep -E "inet[ ]" | awk '{print $2}' | cut -d/ -f1) > /dev/null 2>&1 || true
+    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $(docker exec $GUEST_LABEL_NAME ip addr show eth0 |grep -E "inet[ ]" | awk '{print $2}' | cut -d/ -f1) > /dev/null 2>&1 || true
 else
     echo "Warning: arping not found;"
 fi
@@ -289,11 +292,10 @@ if [[ $STAT_GUEST -ne 0 ]]; then
 fi
 # Print some useful info
 if [ $DEBUG -eq 1 ] ; then
-  network-wrapper inspect $SHORTGUESTNAME
+  network-wrapper inspect $GUEST_LABEL_NAME
 fi
 # Remove NSPID to avoid `ip netns` catch it.
 [ -f /var/run/netns/$NSPID ] && rm -f /var/run/netns/$NSPID
 # Added a debug printout to let know that the script ran to completion successfully.
 echo network-wrapper configuration successful: $GUEST_LABEL_NAME
 exit 0
-
